Repository ivanms1/project-shelf, pull requests merged in 2021-02, with the labels that each got.

#43 Update/card v2
  client/src/Routes/Routes.js
  client/src/assets/Star.svg
  client/src/assets/email.svg
  client/src/assets/github.svg
  client/src/assets/web.svg
  client/src/components/Card/Card.js
  client/src/components/Cardv2/CardDetails/CardDetails.js
  client/src/components/Cardv2/CardDetails/mutationDeleteProject.graphql
  client/src/components/Cardv2/CardDetails/queryGetProject.graphql
  client/src/components/Cardv2/CardDetails/queryUser.graphql
  client/src/components/Cardv2/CardDetails/style.js
  client/src/components/Cardv2/Cardtwo.js
  client/src/components/Cardv2/style.js
  client/src/components/Header/Header.js
  client/src/components/Header/style.js
  client/src/components/PopupModal/PopupModal.js
  client/src/components/PopupModal/style.js
  client/src/helpers/dateConverter.js
  client/src/pages/Home/Home.js
Labels: Card v2 design

#45 Fix/card design
  client/src/components/Cardv2/CardDetails/CardDetails.js
  client/src/components/Cardv2/CardDetails/style.js
  client/src/components/Cardv2/Cardtwo.js
  client/src/components/Cardv2/style.js
  client/src/components/PopupModal/PopupModal.js
  client/src/components/PopupModal/style.js
  client/src/pages/Activated/style.js
  client/src/pages/Edit/Edit.js
  client/src/pages/SubmitYourProject/Submit.js
  client/src/pages/SubmitYourProject/style.js
Labels: fix, fronted

#49 Tags
  api.graphql
  api/graphql.ts
  client/package-lock.json
  client/package.json
  client/src/components/Cardv2/CardDetails/CardDetails.js
  client/src/components/Cardv2/CardDetails/queryGetProject.graphql
  client/src/components/Cardv2/CardDetails/style.js
  client/src/helpers/dateConverter.js
  client/src/pages/SubmitYourProject/SelectOptions/options.js
  client/src/pages/SubmitYourProject/SelectTags/SelectTags.js
  client/src/pages/SubmitYourProject/Submit.js
  client/src/pages/SubmitYourProject/SubmitForm.js
  client/yarn.lock
  package.json
  prisma/schema.prisma
Labels: backend, enhancement, frontend

#72 Cache issue on favorite
  api.graphql
  api/graphql.ts
  client/src/Context/AppContext.js
  client/src/components/Cardv2/CardDetails/CardDetails.js
  client/src/components/Cardv2/CardDetails/mutationDeleteProject.graphql
  client/src/components/Cardv2/Cardtwo.js
  client/src/components/Cardv2/mutationFavoriteProject.graphql
  client/src/components/Cardv2/mutationReactToProject.graphql
  client/src/components/useCurrentUser/queryUseCurrentUser.graphql
  client/src/pages/Edit/Edit.js
  client/src/pages/Edit/queryGetProject.graphql
  client/src/pages/Favorites/Favorites.js
  prisma/schema.prisma
Labels: bug
