Repository ivanms1/project-shelf, pull requests merged in 2021-03, with the labels that each got.

#73 Update/menu dropdown
  client/package.json
  client/src/assets/bell.svg
  client/src/assets/cog.svg
  client/src/components/DropDown/DropDownApp.js
  client/src/components/DropDown/style.module.css
  client/src/components/Header/Header.js
  client/src/components/Header/style.js
  client/src/components/Popper/Popper.js
  client/src/components/Popper/style.js
  client/src/helpers/useOnClickOutside.js
  client/yarn.lock
Labels: update on existing feature

#75 Projects pagination
  api.graphql
  api/graphql.ts
  client/package.json
  client/public/index.html
  client/src/Routes/PrivateRoute.js
  client/src/Routes/PublicRoute.js
  client/src/Routes/Routes.js
  client/src/components/BurgerIcon/BurgerIcon.js
  client/src/components/Cardv2/CardDetails/CardDetails.js
  client/src/components/Cardv2/CardDetails/style.js
  client/src/components/Cardv2/Cardtwo.js
  client/src/components/Cardv2/style.js
  client/src/components/Form/ProjectForm.js
  client/src/components/Header/Header.js
  client/src/components/Header/style.js
  client/src/components/Search/Search.js
  client/src/components/Search/SearchContainerStyle.js
  client/src/components/Spinner/Spinner.js
  client/src/components/Spinner/style.js
  client/src/components/useCurrentUser/queryUseCurrentUser.graphql
  client/src/graphql/projectFragment.graphql
  client/src/helpers/useOnClickOutside.js
  client/src/index.js
  client/src/pages/Activated/Activated.js
  client/src/pages/Activated/queryGetProjects.graphql
  client/src/pages/Admin/Admin.js
  client/src/pages/Admin/Approved/Approved.js
  client/src/pages/Admin/Approved/mutationUpdateProjectStatus.graphql
  client/src/pages/Admin/Approved/queryGetAllApprovedProjects.graphql
  client/src/pages/Admin/Approved/style.js
  client/src/pages/Admin/NotApproved/NotApproved.js
  client/src/pages/Admin/NotApproved/mutationUpdateProjectStatus.graphql
  client/src/pages/Admin/NotApproved/queryGetAllNotApprovedProjects.graphql
  client/src/pages/Admin/NotApproved/style.js
  client/src/pages/Admin/UserTable/JsonData.js
  client/src/pages/Admin/UserTable/Pagination.js
  client/src/pages/Admin/UserTable/UserTable.js
  client/src/pages/Admin/UserTable/mutationUpdateUser.graphql
  client/src/pages/Admin/UserTable/queryGetAllUsers.graphql
  client/src/pages/Admin/UserTable/style.js
  client/src/pages/Admin/style.js
  client/src/pages/Favorites/Favorites.js
  client/src/pages/Favorites/queryGetMyFavoriteProjects.graphql
  client/src/pages/Home/Home.js
  client/src/pages/Home/queryGetMyProjects.graphql
  client/src/pages/Home/queryUser.graphql
  client/src/pages/NotActivated/Notactivated.js
  client/src/pages/NotActivated/queryGetProjects.graphql
  client/src/pages/SubmitYourProject/Submit.js
  client/src/pages/WeeklyProjects/Weekly.js
  client/src/pages/WeeklyProjects/queryGetProjects.graphql
  client/yarn.lock
  package.json
Labels: enhancement

#97 fix cache update on creating and deleting a project
  client/src/components/Cardv2/CardDetails/CardDetails.js
  client/src/pages/SubmitYourProject/Submit.js
Labels: bug
