Repository ivanms1/project-shelf, pull requests merged in 2023-07, with the labels that each got.

#198 chore: move origins to env variable
  apps/api/src/main.ts
Labels: chore

#199 feat: privacy policy and terms & conditions
  apps/web/const/index.tsx
  apps/web/pages/privacy/index.tsx
  apps/web/pages/terms-and-conditions/index.tsx
  apps/web/public/locales/en/common.json
  apps/web/public/locales/en/privacy-policy.json
  apps/web/public/locales/en/terms-and-conditions.json
  apps/web/public/locales/es/common.json
  apps/web/public/locales/es/privacy-policy.json
  apps/web/public/locales/es/terms-and-conditions.json
  apps/web/public/locales/hi/common.json
  apps/web/public/locales/hi/privacy-policy.json
  apps/web/public/locales/hi/terms-and-conditions.json
  apps/web/public/locales/ko/common.json
  apps/web/public/locales/ko/privacy-policy.json
  apps/web/public/locales/ko/terms-and-conditions.json
  apps/web/public/locales/ne/common.json
  apps/web/public/locales/ne/privacy-policy.json
  apps/web/public/locales/ne/terms-and-conditions.json
  apps/web/src/components/Footer/Footer.tsx
  apps/web/src/pages/PrivacyPolicy/Privacy.tsx
  apps/web/src/pages/PrivacyPolicy/index.ts
  apps/web/src/pages/TermsAndConditions/TermsAndConditions.tsx
  apps/web/src/pages/TermsAndConditions/index.ts
Labels: enhancement

#200 rework about page
  apps/web/public/locales/en/about.json
  apps/web/public/locales/es/about.json
  apps/web/public/locales/hi/about.json
  apps/web/public/locales/ko/about.json
  apps/web/public/locales/ne/about.json
  apps/web/src/components/Footer/Footer.tsx
  apps/web/src/pages/About/About.tsx
  apps/web/src/pages/About/Member/Member.tsx
  apps/web/src/pages/PrivacyPolicy/Privacy.tsx
  apps/web/src/pages/TermsAndConditions/TermsAndConditions.tsx
  packages/ui/DropDown/index.tsx
  packages/ui/Floating/index.tsx
  packages/ui/index.ts
  packages/ui/package.json
  yarn.lock
Labels: refactor

#208 chore: update workflow target branch to develop
  .github/workflows/build.yml
  .github/workflows/release-drafter.yml
  apps/api/src/prisma/schema.prisma
Labels: chore

#214 build: revalidate homepage
  apps/web/pages/index.tsx
Labels: enhancement

#215 fix: authors home page hover
  apps/web/src/pages/Home/TopCreator/TopCreator.tsx
  packages/ui/Button/index.tsx
Labels: enhancement

#229 fix private routes being seen
  apps/web/middleware.ts
Labels: bug, fix

#227 fix: like hover color, button size and skeleton UI for card
  apps/admin/src/components/Button/Button.tsx
  apps/web/src/components/CardSkeleton/CardSkeleton.tsx
  apps/web/src/components/Navbar/Navbar.tsx
Labels: bug, fix

#234 fix: remove middleware
  apps/web/middleware.ts
Labels: bug, fix
